openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0

tags:
  - name: Product

paths:
  /Products:
    post:
      operationId: createNewProduct
      summary: Create a new Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        '200':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
      tags:
        - Product

    get:
      operationId: getAllProducts
      summary: Get all Products
      responses:
        '200':
          description: List of all Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDTO'
      tags:
        - Product

  /Products/{id}:
    get:
      operationId: getProductById
      summary: Get Product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
      tags:
        - Product

    put:
      operationId: updateProduct
      summary: Update an Product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDTO'
      tags:
        - Product

    delete:
      operationId: deleteProductById
      summary: Delete an Product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Product deleted successfully
      tags:
        - Product

components:
  schemas:
    ProductDTO:
      $ref: "../models/Product/add-Product.yaml#/components/schemas/ProductDTO"