openapi: 3.0.3
info:
  title: Order API
  version: 1.0.0

tags:
  - name: Orders

paths:
  /orders:
    post:
      operationId: createNewOrder
      summary: Create a new Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderModel'
      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderModel'
      tags:
        - Orders

    get:
      operationId: getAllOrders
      summary: Get all Orders
      responses:
        '200':
          description: List of all Orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderModel'
      tags:
        - Orders

  /orders/{id}:
    get:
      operationId: getOrderById
      summary: Get Order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderModel'
      tags:
        - Orders

    put:
      operationId: updateOrder
      summary: Update an Order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderModel'
      responses:
        '200':
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderModel'
      tags:
        - Orders

    delete:
      operationId: deleteOrderById
      summary: Delete an Order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Order deleted successfully
      tags:
        - Orders

components:
  schemas:
    OrderModel:
      $ref: "../models/order/order.yaml#/components/schemas/OrderModel"