openapi: 3.0.3
info:
  title: Order API
  version: 1.0.0

tags:
  - name: Orders

paths:
  /client-api/v1/orders:
    post:
      operationId: createNewOrder
      summary: Create a new Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderModel'
      responses:
        '200':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Orders
    get:
      operationId: getAllOrders
      summary: Get all Orders
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: sortBy
          in: query
          required: false
          schema:
            type: string
            default: "orderDate"
        - name: sortDirection
          in: query
          required: false
          schema:
            type: string
            default: "DESC"
      responses:
        '200':
          description: get all orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Orders
  /client-api/v1/orders/{id}:
    get:
      operationId: getOrderById
      summary: Get Order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Orders
    put:
      operationId: updateOrder
      summary: Update an Order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderModel'
      responses:
        '200':
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Orders
    delete:
      operationId: deleteOrderById
      summary: Delete an Order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: customer deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
      tags:
        - Orders

components:
  schemas:
    GenericResponse:
      $ref: "../models/generic-response.yaml#/GenericResponse"
    ErrorModel:
      $ref: "../models/error.yaml#/Error"
    OrderModel:
      $ref: "../models/order/order.yaml#/components/schemas/OrderModel"