openapi: 3.0.3
info:
  title: Category API
  version: 1.0.0

tags:
  - name: Categories

paths:
  /client-api/v1/categories:
    post:
      operationId: createNewCategory
      summary: Create a new Category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryModel'
      responses:
        '200':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Categories

    get:
      operationId: getAllCategories
      summary: Get all Categories
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: sortBy
          in: query
          required: false
          schema:
            type: string
            default: "name"
        - name: sortDirection
          in: query
          required: false
          schema:
            type: string
            default: "ASC"
      responses:
        '200':
          description: List of all Categories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Categories

  /client-api/v1/categories/{id}:
    get:
      operationId: getCategoryById
      summary: Get Category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Category found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Categories

    put:
      operationId: updateCategory
      summary: Update an Category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryModel'
      responses:
        '200':
          description: Category updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Categories

    delete:
      operationId: deleteCategoryById
      summary: Delete an Category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Category deleted successfully
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Categories

components:
  schemas:
    GenericResponse:
      $ref: "../models/generic-response.yaml#/GenericResponse"
    ErrorModel:
      $ref: "../models/error.yaml#/Error"
    CategoryModel:
      $ref: "../models/category/category.yaml#/CategoryModel"