openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0

tags:
  - name: Products

paths:
  /client-api/v1/products:
    post:
      operationId: createNewProduct
      summary: Create a new Product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductModel'
      responses:
        '200':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Products

    get:
      operationId: getAllProducts
      summary: Get all Products
      responses:
        '200':
          description: List of all Products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Products

  /client-api/v1/products/{id}:
    get:
      operationId: getProductById
      summary: Get Product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Products

    put:
      operationId: updateProduct
      summary: Update an Product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductModel'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Products

    delete:
      operationId: deleteProductById
      summary: Delete an Product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Product deleted successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Products

components:
  schemas:
    ErrorModel:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: The error code
        message:
          type: string
          description: The error message
      required:
        - code
        - message
    ProductModel:
      $ref: "../models/product/product.yaml#/components/schemas/ProductModel"