#spring:
#  datasource:
#    url: jdbc:h2:mem:customer-service-local
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#logging:
#  level:
#    root: DEBUG
#    com.customer: DEBUG