server:
  port: 8083
  servlet:
    context-path: /customer-service
spring:
  application:
    name: customer-service
  profiles:
    active:
      - true
  datasource:
    url: jdbc:h2:mem:customer-service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:db/changelog/00-master.yaml
    enabled: true
    default-schema: PUBLIC
    contexts:
      - dev
      - prod

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

services:
  base-path:
    order-service: http://localhost:8082/order-service