server:
  port: 8082
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service
  profiles:
    active:
      - true
  datasource:
    url: jdbc:h2:mem:order-service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:db/changelog/0.master.xml # main liquibase file
    enabled: false # Enable Liquibase
    default-schema: PUBLIC # Specify the default schema for H2
    contexts:
      - dev
      - prod

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

services:
  base-path:
    product-service: "http://localhost:8081/product-service"