openapi: 3.0.3
info:
  title: Customer API
  version: 1.0.0

tags:
  - name: Customers

paths:
  /client-api/v1/customer:
    post:
      operationId: createNewCustomer
      summary: Create a new Customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerModel'
      responses:
        '200':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Customers
    get:
      operationId: getAllCustomers
      summary: Get all customer
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: sortBy
          in: query
          required: false
          schema:
            type: string
            default: "name"
        - name: sortDirection
          in: query
          required: false
          schema:
            type: string
            default: "ASC"
      responses:
        '200':
          description: List of all customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Customers

    put:
      operationId: updateCustomer
      summary: Update an Customer by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerModel'
      responses:
        '200':
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Customers

  /client-api/v1/customer/{id}:
    get:
      operationId: getCustomerById
      summary: Get Customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Customer found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Customers
    delete:
      operationId: deleteCustomerById
      summary: Delete an Customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Category deleted successfully
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 400
                message: Invalid request data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
              example:
                code: 500
                message: An unexpected error occurred
      tags:
        - Customers

components:
  schemas:
    GenericResponse:
      $ref: "../models/generic-response.yaml#/GenericResponse"
    ErrorModel:
      $ref: "../models/error.yaml#/Error"
    CustomerModel:
      $ref: "../models/customer/customer.yaml#/CustomerModel"